### ISSUE TITLE
Add missing legal documentation

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/daps-helm-chart#15]
There are two necessary files for legal documentation missing
- `CODE_OF_CONDUCT.md`
- `CONTRIBUTING.md`

This can also be seen on the [Legal Documentation Generator](https://www.eclipse.org/projects/tools/documentation.php?id=automotive.tractusx)

@adkumar1 could you please add these files. These are required for the Eclipse Foundation release

**Comment by adkumar1** [comment]
I have added the files in https://github.com/eclipse-tractusx/daps-helm-chart/pull/16

**Comment by SebastianBezold** [comment]
Why are there Chart version updates included in the PR? I cannot see any changes to the code. Is the bump necessary/wanted?

**Comment by adkumar1** [comment]
When we use the same Chart version, then it does not create release.
It says same version release already exist. So to avoid the conflict we need to bump the Chart version.

**Comment by SebastianBezold** [comment]
Ok understood. Since this is just a missing and required legal documentation, that (for now) is not included in release artifacts, I don't see the need to re-release the Chart. But we can definitely do it
