### ISSUE TITLE
QG 4 checks (Release 3.1.0)

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/daps-helm-chart#22]
## QG checks
Please keep this issue open until QG X is concluded and will be managed by the Issue Creator!
We will inform you about finding and proposals in separated issues, this issue here is for the Overview of the Checks!

### Please keep this issue open until QG4 is concluded!

Product Name: daps-helm-chart
Product Owner: Mehran Roshandel
Dev SPOC: @adkumar1 
Helm Chart Version: `1.7.7`
App Version: `1.7.1`
QG4 Approval: yes/no

##### TRG 1.01
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1
- [x] #23
###### TRG 1.02
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2
- [ ] #24
###### TRG 1.03
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3
- [x] an appropriate `CHANGELOG.md`
    - [x] the versioning itself follows [semantic versioning](https://semver.org/)
##### TRG 2.01
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1
- [x] default branch is named `main`
##### TRG 2.03
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3
- [x] #25
- [x] `/charts` directory contains the Helm chart for the Tractus-X product IF available
- [x] `AUTHORS.md` file (optional)
- [x] #26
- [x] `CONTRIBUTING.md` file
- [ ] `DEPENDENCIES` file(s) with up to date content (Dash tool generated)
- [x] `LICENSE` file
- [x] `NOTICE.md` file
- [x] `SECURITY.md` file
##### TRG 2.04
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4
- [x] #27
- [x] #28
- [x] should contain the release
- [x] references/urls to the product's other repositories
- [x] might contain product helm chart
- [ ] README.md: contains the urls for the backend and frontend applications
##### TRG 2.05
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5
- [x] #29
- [ ] file has a proper format
##### TRG 3.02
https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2
- [x] if data persistence is needed in Kubernetes the use of PersistentVolume and PersistentVolumeClaim resource
##### TRG 4.01
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-1
- [x] All images must be tagged following [semantic versioning](https://semver.org/)
- [x] container is labeled correctly additionally to the latest tag
##### TRG 4.02
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-2
- [x] #30
- [ ] Java, Kotlin, ... if JVM based language use base image from [Eclipse Temurin](https://hub.docker.com/_/eclipse-temurin)
##### TRG 4.03
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-3
- [x] image has `USER` command to specify a non-root user to run the container
- [x] `deployment.yaml` has `runAsUser` and `allowPrivilegeEscalation: false` properly set
##### TRG 4.05
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-5
- [x] released image must be present on `GitHub Package registry` or `Dockerhub`
##### TRG 5.01
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01
- [x] Helm chart must be released
- [x] appropriate semantic versioning for `version` and `appVersion` has to be used in `Chart.yaml`
- [x] #31
- [x] `values.yaml` file must contain proper default values/placeholders
- [x] #33
- [x] Ingress is disabled
- [ ] No references to any secret engine service (e.g.: Hashicorp Vault)
- [x] Dependencies should be prefixed with the nameOverride and/or fullnameOverride properties
- [x] Image tag is set to the `Chart.yaml` `appVersion` property
- [x] #32
- [x] dependencies have to be declared in Chart.yaml NOT requirements.yml
##### TRG 5.02
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02
- [x] Helm chart location inside Git repository in `/charts` directory
- [x] #35
``` markdown
charts/ 
    chartNameA/
      Chart.yaml
      ... 
    chartNameB/
      Chart.yaml
      ...
AUTHORS.md 
DEPENDENCIES.md 
LICENCE 
README.md 
```
- [x] #34
- [x] latest tag is not used in helm chart be default
##### TRG 5.04
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04
- [ ] CPU and memory limits and requests are properly set
##### TRG 5.06
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-06
- [ ] every startup configuration aspect of your application must be configurable through the Helm chart (ingress class, tls, labels, annotations, database, secrets, persistence, env variables)
##### TRG 5.07
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07
- [ ] if dependencies are present in the `Chart.yaml` they are properly configured
##### TRG 5.08
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08
- [ ] a product has a single deployable helm chart that contains all components (backend, frontend, etc.)
- [ ] name of the Chart should be just the product-name without prefix or suffix
- [ ] values file should contain all available variables (even from subcharts) with default values and comments about what they do
- [ ] helm install command should successfully install the chart to any supported Kubernetes version cluster (without overwriting default values)
- [ ] helm test runs without errors

#### Testing
- [ ] installed and running on pre-prod without errors

**Comment by FaGru3n** [comment]
Hi @adkumar1

could you provide us the following information?

``` markdown
Product Name:
Product Owner:
Dev SPOC:
Helm Chart Version:
App Version:
```

**Comment by adkumar1** [comment]
Product Name: DAPS
Product Owner: Mehran Roshandel 
Dev SPOC: Aditya Kumar 
Helm Chart Version: 1.7.7
App Version: 1.7.1
