### ISSUE TITLE
TRG 1.01 - appropriate `README.md` file

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/daps-helm-chart#23]
- Version Mismach within ReadMe
![image](https://github.com/eclipse-tractusx/daps-helm-chart/assets/121097161/986435b3-927f-4f45-9f61-34cbf730e2a9)
 - software version doubeled

- Basic description of repository and its content (Why you need Daps-Server and for what is it?) Why the needed 
- where to get this infrastructure?
> Notice: Tractus-x relies on an IDS-compatible architecture. In that context, a DAPS is needed as an identity server. In this project, we use Fraunhofer's DAPS implementation (https://github.com/Fraunhofer-AISEC/omejdn-server#readme). 
- why the things with frauenhofer DAPS? 

- Installation instructions to get component working
 - how to use daps-sever 
 - if there dependencies how to enable?

**Comment by adkumar1** [comment]
Removed the version section as it is generated inside charts/daps-server

You just need to add image from fraunhofer in values.yaml & get it deployed. 
There are no dependencies

**Comment by Siegfriedk** [comment]
I don't like the Readme very much either but i do have to assume that the reference to frauenhofer is good enough. Please revisit the README @adkumar1 for the next release and challange it with someone who doesn't know daps but needs to use it.

Closing as version is removed, no dependencies to enable
