### ISSUE TITLE
TRG 2.04 - a Leading product repository

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/daps-helm-chart#27]
Each product must have a leading product repository that can point the users to all the parts/components/charts/releases of that product. This can be achieved by having a single repository for a product or creating references to the other repositories.

https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4

would suggest, a leading repo for DAPS within Registration Service and Server

If more questions are needed please talk to @Siegfriedk

**Comment by adkumar1** [comment]
There are  no leading repo. Its an independent component
This repo itself is a leading repo

**Comment by adkumar1** [comment]
@Siegfriedk  I have added it in the PR
