### ISSUE TITLE
TRG 2.04 - repository name must be productname without prefix or suffix

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/daps-helm-chart#28]
repository must contain the product name without prefix or suffix `helm-chart`

or as name of the application itself like your released product "daps-server" https://github.com/eclipse-tractusx/daps-helm-chart/tree/main/charts/daps-server

**Comment by adkumar1** [comment]
It was created by the eclipse contributer long back.
If required it can be changed

**Comment by Siegfriedk** [comment]
@FaGru3n this is actually it. it is a / the helm chart.
