### ISSUE TITLE
TRG 2.05 - `.tractusx` metafile is present in the root of the repository

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/daps-helm-chart#29]
Please add the needed metafile:
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5

**Comment by adkumar1** [comment]
Added with [bd6a352](https://github.com/catenax-ng/tx-daps-helm-chart/commit/bd6a352005ac05b07382382be43c6c0ed45f8cf5)
