### ISSUE TITLE
TRG 4.01 - must add a section to your top level `README.md` file, that contains information about the used base image

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/daps-helm-chart#30]
Hi didn´t found any image repository for your application, could you help me out with that and where i find that your referenced image?

**Comment by adkumar1** [comment]
For your reference below is the image which is used for DAPS.
ghcr.io/fraunhofer-aisec/omejdn-server:1.7.1

According to security team we should not specify this image anywhere in the helm charts & documentation as it is not our product. It is owned by Fraunhofer

**Comment by Siegfriedk** [comment]
we will not mention a base image as we don't have a base image.
