### ISSUE TITLE
TRG 5.01 - must not contain any environment specific `values-xyz.yaml`

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/daps-helm-chart#31]
Hi regarding to TRG:
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01
> The released Helm chart must not contain any environment specific values-xyz.yaml files

https://github.com/eclipse-tractusx/daps-helm-chart/tree/daps-server-1.7.7/charts/daps-server
![image](https://github.com/eclipse-tractusx/daps-helm-chart/assets/121097161/ae6a80ca-b1b7-4bac-8ed0-a56b141b3d9b)

**Comment by adkumar1** [comment]
If we will remove environment specific values-xyz.yaml file.
Then how we will deploy to different environments ?

**Comment by Siegfriedk** [comment]
.helmignore exist and should be enough. we can discuss this after the release. closing the ticket for now
