### ISSUE TITLE
must be deployable to any environment without overwriting default values with a simple helm install command

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/daps-helm-chart#32]
Hi all,

Test with a kind cluster did not worked as expected  with your guides to install the daps-server.
https://github.com/eclipse-tractusx/daps-helm-chart/blob/main/INSTALL.md

Maybe a good documentation how to install your helm chart, would be better.

**Comment by adkumar1** [comment]
Installation steps are proper. We are not allowed to define outside image in helm charts. That is why you are not able to install the app. Firstly you need to define image in values.yaml, post that you wil be able to deploy

**Comment by Siegfriedk** [comment]
@adkumar1 and you are also not allowed to add a hint to the image?

**Comment by adkumar1** [comment]
I am not sure about that. As per Security team instruction earlier we were not allowed to mention image name.

**Comment by Siegfriedk** [comment]
@adkumar1 please add a hint in sense of "You can use your own images, one available image is available at the frauenhofer ..." adding an image hint should not be illegal. Please add it

**Comment by Siegfriedk** [comment]
closing this as we do have a hint on the README/INSTALL.d
